---
title: Patrick Reagan Running
timezone: UTC
collections:
  pages:
    title: Custom Pages
    output: true
    permalink: "/:name"
  dataMedia:
    title: Media Data
    output: false
  posts:
    title: Posts
    output: true
  dataRacing:
    title: Racing Data
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/journal/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: Test site for Patrick
baseurl: ''
email: patrickreaganrunning@gmail.com
social:
- platform-name: Instagram
  username: patrickreaganrunning
  url: https://www.instagram.com/patrickreaganrunning/
- platform-name: Strava
  username: Patrick Reagan
  url: https://www.strava.com/pros/10014836
- platform-name: Twitter
  username: preaganrunning
  url: https://www.twitter.com/preaganrunning/
- platform-name: Facebook
  username: patrickreaganrunning
  url: https://www.facebook.com/patrickreaganrunning/
coaching-callout:
  title: Ready to run&nbsp;fast?
  description: We are intrinsically bound to our own rhythms and struggles until we
    seek the perspective of others. Let’s work together to find your stride.
  cta: Coaching Services
  cta-link: "/coaching"
